name: Deploy FEP App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: ${{ secrets.AWS_REGION }}
      VPC_ID: ${{ secrets.VPC_ID }}
      SUBNET_ID_1: ${{ secrets.SUBNET_ID_1 }}
      SUBNET_ID_2: ${{ secrets.SUBNET_ID_2 }}
      ALB_SG_ID: ${{ secrets.ALB_SG_ID }}
      ALB_LISTENER_ARN: ${{ secrets.ALB_LISTENER_ARN }}
      BACKEND_ECR_REPO: ${{ secrets.BACKEND_ECR_REPO }}
      FRONTEND_ECR_REPO: ${{ secrets.FRONTEND_ECR_REPO }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: terraform init
        working-directory: terraform

      - name: Terraform Plan
        run: terraform plan -var="aws_region=${{ env.AWS_REGION }}" -var="vpc_id=${{ env.VPC_ID }}" -var="subnet_ids=[\"${{ env.SUBNET_ID_1 }}\",\"${{ env.SUBNET_ID_2 }}\"]" -var="alb_sg_id=${{ env.ALB_SG_ID }}" -var="alb_listener_arn=${{ env.ALB_LISTENER_ARN }}" -var="backend_repo_name=${{ env.BACKEND_ECR_REPO }}" -var="frontend_repo_name=${{ env.FRONTEND_ECR_REPO }}"
        working-directory: terraform

      - name: Terraform Apply
        run: terraform apply -auto-approve -var="aws_region=${{ env.AWS_REGION }}" -var="vpc_id=${{ env.VPC_ID }}" -var="subnet_ids=[\"${{ env.SUBNET_ID_1 }}\",\"${{ env.SUBNET_ID_2 }}\"]" -var="alb_sg_id=${{ env.ALB_SG_ID }}" -var="alb_listener_arn=${{ env.ALB_LISTENER_ARN }}" -var="backend_repo_name=${{ env.BACKEND_ECR_REPO }}" -var="frontend_repo_name=${{ env.FRONTEND_ECR_REPO }}"
        working-directory: terraform

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build backend image
        run: |
          docker build -t ${{ env.BACKEND_ECR_REPO }} ./backend
          docker tag ${{ env.BACKEND_ECR_REPO }}:latest ${{ steps.login-ecr.outputs.registry }}/${{ env.BACKEND_ECR_REPO }}:latest
          docker
