name: Deploy Funeral App FEP

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: eu-west-2

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build and push backend image
      env:
        AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
        AWS_REGION: ${{ env.AWS_REGION }}
      run: |
        cd backend
        BACKEND_REPO="${{ secrets.BACKEND_ECR_REPO }}"
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin "$BACKEND_REPO"
        docker build -t $BACKEND_REPO:latest .
        docker push $BACKEND_REPO:latest
        echo "BACKEND_IMAGE_URI=$BACKEND_REPO:latest" >> $GITHUB_ENV

    - name: Build and push frontend image
      env:
        AWS_DEFAULT_REGION: ${{ env.AWS_REGION }}
        AWS_REGION: ${{ env.AWS_REGION }}
      run: |
        cd ../frontend
        FRONTEND_REPO="${{ secrets.FRONTEND_ECR_REPO }}"
        aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin "$FRONTEND_REPO"
        docker build -t $FRONTEND_REPO:latest .
        docker push $FRONTEND_REPO:latest
        echo "FRONTEND_IMAGE_URI=$FRONTEND_REPO:latest" >> $GITHUB_ENV

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init
      run: cd terraform && terraform init

    - name: Terraform Apply
      run: |
        cd terraform
        terraform apply -auto-approve \
          -var="vpc_id=${{ secrets.VPC_ID }}" \
          -var="subnet_ids=[\"${{ secrets.SUBNET_ID_1 }}\",\"${{ secrets.SUBNET_ID_2 }}\"]" \
          -var="alb_listener_arn_https=${{ secrets.ALB_LISTENER_ARN }}" \
          -var="alb_security_group_id=${{ secrets.ALB_SG_ID }}" \
          -var="backend_image=${{ env.BACKEND_IMAGE_URI }}" \
          -var="frontend_image=${{ env.FRONTEND_IMAGE_URI }}"
